Frontend sprint8 update lei
Fullstack-Roligheter/Frontend-ReactTS pull request #13
Opened 2022-09-05 07:58 UTC by Saru444

Fixat routern då den inte följde hur react-router-dom fungerar. Samt lite småfix på styling.

2022-09-05 14:37 UTC, MikaelaNystrom requested changes

2022-09-05 14:37 UTC, MikaelaNystrom commented on src/shared/layout/sidebar/sidebar.tsx
> -    { title: 'About us', route: `/${props.user}/omoss` },
För att man ska kunna navigera till dessa som inloggad så ligger ${props.user}/ här för att kunna känna av vem som är inloggad och vems info som ska läsas in samt kolla om någon alls är inloggad eller om man ska rediectas till logIn. Det behöver vara kvar.

2022-09-06 07:39 UTC, MikaelaNystrom approved these changes

2022-09-06 09:16 UTC, CanoodlingSocks approved these changes
Ser bra ut

2022-09-06 09:16 UTC, merged