Category List och Modal Ändringar
Fullstack-Roligheter/Frontend-ReactTS pull request #43
Opened 2022-10-19 10:56 UTC by Krezeb

### Commit 1: Refaktorisering

>_deleteCategoryModal.tsx:_
> - Flyttat DeleteCategoryModelProps Interface till Interface mappen.
> - Raderat en onödig variabel.
> - Flyttat onConfirm till rätt plats.
> - Flyttat setLoadingState för att spinners ska inte stannar kvar.
> - Flyttat callBack.
> - Använt Typescript i formen.

>_editCategoryModal.tsx:_
> - Flyttat EditCategoryModelProps Interface till Interface mappen.
> - Lagt i en e.preventDefault().
> - Plockat bort onödliga console.logs.
> - Flyttat setLoadingState för att spinners ska inte stannar kvar.
> - Flyttat callBack så kategorilistan uppdateras efter modalen försvinner.

>_createCategoryModal.tsx:_
> - Flyttat CreateCategoryModelProps Interface till Interface mappen.
> - Bytt namn på varablerna från svenska till engelska.
> - Översatt Modalen till engelska.

>_userprofile.tsx_
> - Byter onConfirmDelete till onConfirm i DeleteModal elementet.
> - Raderat oanvänt kod.

>_categoryModal.tsx_
> - Här ligger alla interfaces.

---
### Commit 2: Mer Refaktorisering

>_editCategoryModal.tsx:_
> - Bytte variabelnamn från svenska till engeska.
> - Använder Typescript i formen.
> - Formen nu tar emot oldCategoryName och använder den i formen.
> - Översatt formen till englelska.
> - Ändrat formen: Den använder onSubmit istället för onClick.

>_newCategoryModal.tsx:_
> - Byter tillbaka en variablenamn.

> _userProfile.tsx:_
> - Skickar categoryOldName som prop till EditCategoryModal.

>_categoryModal.tsx:_
> - Ändrat en prop namn som används i newCategoryModal.
> - Lagt till categoryOldName i EditCategoryModalProps.

---
### Commit 3: Mer Refactoring + Placeholders

>_deleteCategoryModal.tsx:_
> - Byter från dubbla handelSumbit till en.

>_newCategoryModal.tsx:_
> - Skapat en random placeholder i formen.

>_useerProfile.tsx:_
> - Översatt props från svenska till engelska.

---
### Commit 4: Felsökning:

>_deleteCategoryModal.tsx:_
> - Ändrat <React.Fragment> till <>.
> - Plockat bort Button Nesting.
> - Raderat onödiga Imports.

>_editCategoryModal.tsx:_
> - Plockat bort Button Nesting.
> - Raderat onödiga Imports.

>_newCategoryModal.tsx:_
> - Plockat bort Button Nesting.
> - Raderat onödiga Imports.
> 

>_userProfile.tsx:_
> - Ändrat <React.Fragment> till <>.
> - Bytte ut "li:nth-child(even)" mot "'li:nth-of-type(even)".

>_button-defaullt.tsx:_
> - Skapat en Box runt Button i DisabledSubmitButton.

>_modal.tsx:_
> - Ändrat <React.Fragment> till <>.
> - Ändrat Imports och plockat bort onödiga.
> - Prettier omformatering.

2022-10-19 11:04 UTC, MikaelaNystrom commented on src/features/deleteCategorModal/deleteCategoryModal.tsx
> -    <React.Fragment>
Enligt guiden jag utgick ifrån behövde den vara en react fragment för att fungera som en modal, det var iof när den låg nestad i grundkoden. Beter den sig som tänkt när du tar bort react.fragment?

2022-10-19 11:05 UTC, Krezeb commented
![](https://github.trello.services/images/mini-trello-icon.png) [UserCategories listan uppdaterar direkt på frontend efter Delete](https://trello.com/c/NVeYAyVk/153-usercategories-listan-uppdaterar-direkt-p%C3%A5-frontend-efter-delete)

2022-10-19 11:05 UTC, Krezeb commented
![](https://github.trello.services/images/mini-trello-icon.png) [UserCategories listan uppdaterar direkt på frontend efter Create](https://trello.com/c/w59dxpt9/150-usercategories-listan-uppdaterar-direkt-p%C3%A5-frontend-efter-create)

2022-10-19 11:05 UTC, Krezeb commented
![](https://github.trello.services/images/mini-trello-icon.png) [UserCategories listan uppdaterar direkt på frontend efter Edit](https://trello.com/c/IGycxH3L/152-usercategories-listan-uppdaterar-direkt-p%C3%A5-frontend-efter-edit)

2022-10-19 11:05 UTC, Krezeb commented
![](https://github.trello.services/images/mini-trello-icon.png) [Införa Random Placeholders i CreateNewCategory](https://trello.com/c/iJ3wQrwD/154-inf%C3%B6ra-random-placeholders-i-createnewcategory)

2022-10-19 11:06 UTC, Krezeb commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactorisera deleteCategoryModal.tsx](https://trello.com/c/ARkAxpNI/157-refactorisera-deletecategorymodaltsx)

2022-10-19 11:06 UTC, Krezeb commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactorisera editCategoryModal.tsx](https://trello.com/c/oW9aqD92/156-refactorisera-editcategorymodaltsx)

2022-10-19 11:07 UTC, MikaelaNystrom commented on src/features/expense/ExpenseDashboard.tsx
> +                      message='Skriv in namn på nya kategorin'
Inte översatt

2022-10-19 11:08 UTC, MikaelaNystrom commented on src/features/expense/ExpenseDashboard.tsx
> +              Tryck på plusset för att lägga till en ny kategori
Inte översatt

2022-10-19 11:12 UTC, MikaelaNystrom requested changes
Se kommentarer

2022-10-19 11:17 UTC, Krezeb commented on src/features/expense/ExpenseDashboard.tsx
> +                      message='Skriv in namn på nya kategorin'
Varför expense dashboard följde med vet jag inte riktigt. Jag öppnande säkert bara och sparade av ren reflex. Jag har själv inte ändrat nåt i den här filen, bara prettier som gör sitt. Jag tänker inte ändra nåt här, översättningen får komma med i en annan kort.

2022-10-19 11:18 UTC, Krezeb commented on src/features/expense/ExpenseDashboard.tsx
> +              Tryck på plusset för att lägga till en ny kategori
Varför expense dashboard följde med vet jag inte riktigt. Jag öppnande säkert bara och sparade av ren reflex. Jag har själv inte ändrat nåt i den här filen, bara prettier som gör sitt. Jag tänker inte ändra nåt här, översättningen får komma med i en annan kort.

2022-10-19 11:20 UTC, Krezeb commented on src/features/deleteCategorModal/deleteCategoryModal.tsx
> -    <React.Fragment>
<> är en <React.Fragment>
Facebook har bara kortat ner den.

2022-10-19 22:14 UTC, Bergewing approved these changes

2022-10-20 13:08 UTC, Kjellberg90 approved these changes

2022-10-21 12:18 UTC, CanoodlingSocks approved these changes

2022-10-21 12:20 UTC, merged